Add Contact form
Surafels/Portfolio_mobile pull request #4
Opened 2023-06-14 06:08 UTC by Saritalitu23

Add form section & Validation to portfolio mobile 
update the code for index.html & style.css.

2023-06-14 06:17 UTC, wayungi reviewed
Hi @Saritalitu23 , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project with an unprofessional readme. Kindly use the microverse template. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-14 10:21 UTC, Saritalitu23 commented
Please be more specific .i am unable understand so i am stuck .

On Wed, Jun 14, 2023 at 11:47 AM Francis Wayungi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @Saritalitu23 <https://github.com/Saritalitu23> ,
> [image: image]
> <https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png>
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request ❌ ❌
>
>    - You have submitted a project with an unprofessional readme. Kindly
>    use the microverse template.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Surafels/Portfolio_Mobile/pull/4#pullrequestreview-1478561585>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25JRKU3VC7X25QKFZFGDOLXLFJO7ANCNFSM6AAAAAAZF23NWI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-14 10:35 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @Saritalitu23 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Form is properly validated ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 10:35 UTC, AbelG101 commented on styles.css
> +}
- [ ] Ouch! this is very close but it seems like the background image in your design is a bit misaligned as some of the icons in the background image are not in position as shown in the Figma design. As a frontend developer, It's very important you pay attention to small details like this as they give your UI a more polished feel. 😉
- Your design:
  ![image](https://github.com/Surafels/Portfolio_Mobile/assets/104968236/a67935da-9f75-4a52-9a7d-6ec6b6fe64d2)
- Figma design:
  ![image](https://github.com/Surafels/Portfolio_Mobile/assets/104968236/89afdcad-61b9-48de-9cf9-8a524ce3bf65)

2023-06-14 10:35 UTC, AbelG101 commented on styles.css
- [ ] Also pelase make sure you use the given font from the Figma design which is "Poppins" I noticed you forgot to add the proper import statement in your styles file, you just have to copy and paste the below code at the top of your styles file, so they get imported 👇
```css
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,900;1,500;1,600&display=swap');
```
- [ ] Also, please make sure all of the texts in your contract section use the "Poppins" font as I noticed the paragraph is using the default browser font.
- Your design:
  ![image](https://github.com/Surafels/Portfolio_Mobile/assets/104968236/328a122e-9b85-4b81-81a7-0f9dfcbf8087)

2023-06-17 08:41 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @Saritalitu23,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-17 08:52 UTC, skyv26 reviewed
## Hi @Saritalitu23, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🟨 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWE2ZmNjNGRhOGMxM2RiYzA1MmQ0NjI3YzA4OTZlZDRhZWEzMGJmOSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/tSgvKtecVrK8j6ys3e/giphy.gif)


## Reason 🗒️ 
You have submitted a project, that is not your repository PR, please submit your repository PR for getting a review. Don't use your partner PR for getting approval.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-04 15:18 UTC, merged