Update about me styles
Surafels/Portfolio_mobile pull request #6
Opened 2023-07-04 15:56 UTC by Surafels

Mobile Version Portfolio

- Added introduction section
- Added cards
- Added about me section

2023-07-04 16:53 UTC, Strangeal requested changes
Hi @Surafels, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
- [ ] Kindly consider formatting your `README` file properly for it to be more readable. You have all the essential information in there but it's not formatted properly and due to that, it makes reading it uneasy so I would suggest taking a look at how the [original template](https://github.com/microverseinc/readme-template) has been formatted and doing the same.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 16:53 UTC, Strangeal commented on styles.css
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L56
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L142
- [ ] Great job on implementing the second milestone of your portfolio project as specified in the project requirement! 👏 However, there are minor issues 🐞 that we need to address and fix.
  - [ ] Kindly consider adding a `hover` effect to all your `button` to match the `Figma` design. It would enhance the user experience and provide visual feedback.
  - [ ] Consider adding appropriate CSS properties to match that of the `Figma` design such as background and text color to create the desired hover effect. See below for more details on the colors to use:
  
<img width="762" alt="Screenshot 2023-07-04 at 16 07 07" src="https://github.com/Surafels/Portfolio_Mobile/assets/107192076/c9616359-9dc7-4559-984e-96bef0789e8f">

2023-07-04 16:53 UTC, Strangeal commented on index.html
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L83
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L126
- [ ] Kindly note 📝 that it's important to have only one `h1` tag on a web page because the `h1` tag serves as the main heading of the page and gives an overall context of what the page is about. Search engines also use the `h1` tag to understand the topic of the page and determine its relevance to a search query. If there are multiple `h1` tags on a page, it can confuse search engines and lead to lower visibility in search results. In addition, having multiple `h1` tags can also make it difficult for users with screen readers or other assistive technologies to understand the structure and content of the page.
  - [ ] Instead of using an `h1` tag multiple times, consider using other heading tags such as (`h2, h3, h4, h5, h6`).

2023-07-04 16:53 UTC, Strangeal commented on index.html
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L133

- [ ] Kindly consider the use of heading (`h2`, `h3`, `h4`) tags instead of the `p` tag to display the **LET'S CONNECT** text as it is a sub-heading of the main(**About Myself**) heading. Using heading tags conveys the semantic meaning of a subheading and helps improve the accessibility and structure of the document. Therefore, using heading tags instead of the `p` tag would be more semantically correct in this context.

2023-07-04 16:53 UTC, Strangeal commented on index.html
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L134-L140

- [ ] Kindly consider wrapping each `icon` with an `a` tag. This will provide a better user experience by allowing users to easily connect with you through your social media handles. By associating each `icon` with an `a` tag, it conveys the intention of linking to your social media profiles. This way, users can click on the icons and be directed to the corresponding social media platforms.

2023-07-04 16:53 UTC, Strangeal commented on index.html
https://github.com/Surafels/Portfolio_Mobile/blob/bb4981ddec17a667c3a52d7bd1ac2e048714826f/index.html#L143-L163

- Kindly consider using `ul` (unordered list) and `li` (list item) tags to create your languages section. You can achieve this by nesting the `li` tags within the `ul` tag. This will ensure proper semantic structure and improve the readability of your code. Example: 
```
     <ul class="languages">
        <li>class="language">Languages
            <ul>
            <li>Black tea</li>
            <li>Green tea</li>
           </ul>
        </li>
        <li class="frameworks">Frameworks</li>
        <li class="lan-skill">Skills</li>
     </ul>
```

2023-07-04 20:45 UTC, usorfaitheloho requested changes
> Hi @Surafels  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Good and Descriptive README file✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 20:45 UTC, usorfaitheloho commented on index.html
As suggested by the previous reviewer, kindly use the `<ul><li></li></ul>` tag for the `languages`, `skills`, and `framework` section of your project  to show good semantics and good use of HTML tags 😄

2023-07-06 11:57 UTC, osamaashraf6 approved these changes
Hi @Surafels  😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (3)](https://github.com/HtetWaiYan7191/math-magicians/assets/83360636/a4187e50-1df4-484c-a779-5ff1f9078d40)

## Highlights🎉🎉


- [ ]  Following Figma design 🚀
- [ ] Nice design 👌
- [ ] Use the semantics tags 🥇


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 12:11 UTC, merged